### ISSUE TITLE
Vulkan implementation does not free any objects

### ISSUE THREAD

**Issue by MuffinTastic** [xezno/mocha#47] opened 2023-02-03 00:38 UTC
This won't cause us problems in our little test scene, but as soon as we have dynamic scenes that are even remotely complex/detailed I have a good feeling it's gonna eat up RAM/VRAM and fast. I tried to hunt down all of the allocations, deleting the objects owned by the render context and implementing VulkanObject::Delete() on all the object classes, but some seem to elude me, as when I call `vmaDestroyAllocator( m_allocator )` after freeing everything I could find, I get this

![devenv_uh9gEskVTw](https://user-images.githubusercontent.com/10884425/216482539-ecb638cb-0668-4987-8ef1-cb7d93fa3e62.png)

**Comment by xezno** [comment] 2023-02-04 00:38
This is now fixed on our end in the rendering/deletion-queue branch.
You might notice that there are a few objects that aren't getting destroyed - those aren't ours, I think it's caused by [ocornut/imgui#3743](https://www.github.com/ocornut/imgui/issues/3743) but I'm not 100% sure.

**Comment by xezno** [comment] 2023-02-04 02:12
There were a few things I missed when I posted that, calling `vmaDestroyAllocator` now works as of https://github.com/xezno/mocha/commit/7bfddf0eb876a21e1215c6c2f84e64bfe30851bd.

**Closed** 2023-03-04 21:05 UTC
Labels: context/native, system/rendering
